export const exerciseData = [
  {
    _id: '627e46aef7813f118e897115',
    title: {
      en: 'Steady Clamp',
      ar: 'ثابت المشبك',
    },
    description: {
      en: 'Slowly contract the PF muscle to the max tension over 3 seconds. Keep them tight for 5 seconds at the max tension point. Then slowly relax the PF muscles over 3 seconds.',
      ar: 'قم بشد عضلة PF ببطء إلى أقصى توتر خلال 3 ثوان. احتفظ بها مشدودة لمدة 5 ثوانٍ عند أقصى نقطة توتر. ثم ارخي ببطء عضلات PF على مدى 3 ثوان.',
    },
    time: 31,
    delay: 3,
    text: ['Squeeze Slowly', 'Hold', 'Relax slowly'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627e43fcf7813f118e897112',
    title: {
      en: 'Trembling',
      ar: 'يرتجف',
    },
    description: {
      en: 'Contract the PF muscles when your phone vibrates. Relax them when the vibration is over. Repeat this for as long as your phone tells you.',
      ar: 'قلص عضلات PF عندما يهتز هاتفك. استرخى عند انتهاء الاهتزاز. كرر هذا طالما يخبرك هاتفك.',
    },
    time: 24,
    delay: 1,
    text: ['Contract', 'Relax'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627e4355f7813f118e89710f',
    title: {
      en: 'Steady Trembling',
      ar: 'يرتجف بثبات',
    },
    description: {
      en: 'Contract the PF muscles. Keep them tight for 2 seconds at the max tension point. Then relax. Keep the rhythm.',
      ar: 'عقد عضلات PF. احتفظ بها مشدودة لمدة ثانيتين عند أقصى نقطة توتر. ثم استرخ. حافظ على الإيقاع.',
    },
    time: 24,
    delay: 2,
    text: ['Squeeze & hold', 'Relax'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627e3a42f7813f118e89710c',
    title: {
      en: 'Waves',
      ar: 'أمواج',
    },
    description: {
      en: 'Contract the PF muscles at half strength. Keep them tight for 1 second. Then contract the PF muscles at full strength. Keep them tight for 1 second. Relax.',
      ar: 'قم بشد عضلات PF بنصف قوة. احتفظ بها مشدودة لمدة ثانية واحدة. ثم قم بشد عضلات PF بكامل قوتها. احتفظ بها مشدودة لمدة ثانية واحدة. الاسترخاء.',
    },
    time: 26,
    delay: 2,
    text: ['Squeeze halfway', 'Squeeze fully', 'Relax'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627e3946f7813f118e897109',
    title: {
      en: 'Long steady clamp',
      ar: 'مشبك ثابت طويل',
    },
    description: {
      en: 'Slowly contract the PF muscle to the max tension over 3 seconds. Keep them tight for 8 seconds at the max tension point. Then slowly relax the PF muscles over 3 seconds.',
      ar: 'قم بشد عضلة PF ببطء إلى أقصى توتر خلال 3 ثوان. احتفظ بها مشدودة لمدة 8 ثوانٍ عند أقصى نقطة توتر. ثم ارخي ببطء عضلات PF على مدى 3 ثوان..',
    },
    time: 40,
    delay: 3,
    text: ['Squeeze slowly', 'Hold', 'Relax slowly'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627d051c8b3b950442d25aae',
    title: {
      en: 'Upstairs',
      ar: 'الطابق العلوي',
    },
    description: {
      en: 'Start squeezing the PF muscles gradually in 4 steps. Pause briefly at eac step. Then completely relax the PF muscles. Kepp the rhythm.',
      ar: 'ابدأ في الضغط على عضلات PF تدريجيًا في 4 خطوات. توقف لفترة وجيزة في خطوة إي سي. ثم قم بإرخاء عضلات PF تمامًا. حافظ على الإيقاع.',
    },
    time: 25,
    delay: 2,
    text: [
      'Squeeze slightly',
      'Squeeze Halfway',
      'Squeeze more',
      'Squeeze fully',
      'Relax',
    ],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627d04228b3b950442d25aab',
    title: {
      en: 'Reverse Clamp',
      ar: 'عكس المشبك',
    },
    description: {
      en: 'Quickly contract the PF muscles as hard as you can. Then relax them over 3 seconds. Keep the rhythm.',
      ar: 'قم بشد عضلات PF بسرعة بأقصى قوة ممكنة. ثم أرخهم لمدة 3 ثوان. حافظ على الإيقاع.',
    },
    time: 29,
    delay: 1.5,
    text: ['Squeeze', 'Relax Slowly'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627d035a8b3b950442d25aa8',
    title: {
      en: 'Pulsation',
      ar: 'نبض',
    },
    description: {
      en: 'Contract the PF muscles at half strength. Relax, Then contract the PF muscles at full strength and keep them tight for 1 second. Relax. Keep the rhythm.',
      ar: 'قم بشد عضلات PF بنصف قوة. استرخ ، ثم قم بشد عضلات PF بكامل قوتها واحتفظ بها مشدودة لمدة ثانية واحدة. الاسترخاء. حافظ على الإيقاع.',
    },
    time: 35,
    delay: 2,
    text: ['Squeeze more', 'Relax', 'Sqeeze fully'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627d02488b3b950442d25aa5',
    title: {
      en: 'Starter',
      ar: 'بداية',
    },
    description: {
      en: 'Quickly contract and relax the PF muscles. Then contract the PF muscles again and keep them tight for 3 seconds. Relax. Keep the rhythm.',
      ar: 'قبض بسرعة واسترخي عضلات PF. ثم شد عضلات PF مرة أخرى واحتفظ بها مشدودة لمدة 3 ثوانٍ. الاسترخاء. حافظ على الإيقاع.',
    },
    time: 29,
    delay: 2,
    text: ['Contract', 'Relax', 'Squeeze & Hold'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627d00d08b3b950442d25aa2',
    title: {
      en: 'Reverse Keggel',
      ar: 'عكس كيجل',
    },
    description: {
      en: 'Tighten the abdominal muscles for 5 seconds as if you are trying to pee faster. Transfer this pressure as low as you can from your abs to the penis. Then rest for 5 seconds.',
      ar: 'شد عضلات البطن لمدة 5 ثوان كما لو كنت تحاول التبول بشكل أسرع. انقل هذا الضغط إلى أدنى مستوى ممكن من القيمة المطلقة إلى القضيب. ثم الراحة لمدة 5 ثوان.',
    },
    time: 23,
    delay: 4,
    text: ['Push', 'Relax'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627cfff78b3b950442d25a9f',
    title: {
      en: 'Short Holding',
      ar: 'عقد قصير',
    },
    description: {
      en: 'Squeeze the PF muscles as hard as you can. Keep them tight for 4 seconds. Then rest for 4 seconds. Remembre to breathe.',
      ar: 'اضغط على عضلات PF بأقصى ما تستطيع. احتفظ بها مشدودة لمدة 4 ثوان. ثم الراحة لمدة 4 ثوان. تذكر أن تتنفس.',
    },
    time: 25,
    delay: 5,
    text: ['Sqeeze & Hold', 'Relax'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627cff0b8b3b950442d25a9c',
    title: {
      en: 'Downstairs',
      ar: 'الطابق السفلي',
    },
    description: {
      en: 'Squeeze the PF muscles as hard as you can. Then start relaxing them gradually in 4 steps. Pause briefly at each step.',
      ar: 'اضغط على عضلات PF بأقصى ما تستطيع. ثم ابدأ في إرخائهم تدريجيًا في 4 خطوات. توقف لفترة وجيزة في كل خطوة.',
    },
    time: 25,
    delay: 3,
    text: [
      'Relax slightly',
      'Relax halfway',
      'Relax more',
      'Relax fully',
      'Contract',
    ],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627cfdd18b3b950442d25a99',
    title: {
      en: 'Clamp',
      ar: 'المشبك',
    },
    description: {
      en: 'Slowly contract the PF muscles to the max tension over 3 seconds. Ten slowly relax them over 3 seconds.Keeo the rythm.',
      ar: 'قم بشد عضلات PF ببطء حتى تصل إلى أقصى شد على مدى 3 ثوان. عشر منها استرخي ببطء على مدى 3 ثوان.',
    },
    time: 29,
    delay: 3,
    text: ['Sqeeze slowly', 'Relax slowly'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627cfcb38b3b950442d25a96',
    title: {
      en: 'Elevator',
      ar: 'مصعد',
    },
    description: {
      en: 'Start squeezing the PF muscle gradually in 4 steps. Pause briefly at each step. Then relax them the same way.',
      ar: 'ابدأ في الضغط على عضلة PF تدريجيًا في 4 خطوات. توقف لفترة وجيزة في كل خطوة. ثم استرخيهم بنفس الطريقة.',
    },
    time: 35,
    delay: 5,
    text: [
      'sqeeze slighty',
      'squeeze halfway',
      'squeeze more',
      'squeeze fully',
      'Relax halfway',
      'Relax more',
      'Relax fully',
    ],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627cfa768b3b950442d25a93',
    title: {
      en: 'Front Clamp',
      ar: 'المشبك الأمامي',
    },
    description: {
      en: 'Slowly contract the PF muscles over 3 seconds to max tension. Then quickly relax them. Keep the rhythm.',
      ar: 'قم بشد عضلات PF ببطء على مدى 3 ثوان لأقصى شد. ثم استرخيهم بسرعة. حافظ على الإيقاع.',
    },
    time: 34,
    delay: 2,
    text: ['sqeeze slowly'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627ba1690a16cbfbf8d516fb',
    title: {
      en: 'Flash',
      ar: 'فلاش',
    },
    description: {
      en: 'Contract and relax the PF muscle very quickly by following phone vibration. Keep the rythym',
      ar: 'قم بشد وإرخاء عضلة PF بسرعة كبيرة باتباع اهتزاز الهاتف. حافظ على الإيقاع',
    },
    time: 9,
    delay: 1,
    text: ['Contract quickly'],
    is_active: true,
    is_enable: true,
  },
  {
    _id: '627ba0420a16cbfbf8d516f8',
    title: {
      en: 'Holding',
      ar: 'تحتجز',
    },
    description: {
      en: "Squeeze the PF muscle as hard as you can. Keep them tight for as long as your phone tells you. Don't strain other muscles. Remember to breath",
      ar: 'اضغط على عضلة PF بأقصى ما تستطيع. احتفظ بها ضيقة طالما أن هاتفك يخبرك. لا تجهد عضلات أخرى. تذكر أن تتنفس',
    },
    time: 12,
    delay: 1,
    text: ['Squeeze & hold'],
    is_active: true,
    is_enable: true,
  },
];
